version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    network_mode: "host"
    ports:
      - "80:80"
      - "443:443"  # Для HTTPS
    volumes:
      - ./config/conf.d:/etc/nginx/conf.d
    restart: unless-stopped

volumes:
  grafana_data:
