version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    network_mode: "host"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped

volumes:
  grafana_data:
