services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    network_mode: "host"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/dashboards.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./dashboards:/var/lib/grafana/dashboards
    restart: unless-stopped

volumes:
  grafana_data:
