{
 "title": "Fluentd dashboard (Prometheus exporter)",
 "description": "A quick dashboard for displaying Fluentd metrics.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Output status emit records",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(fluentd_output_status_emit_records[5m])"
    }
   ]
  },
  {
   "title": "buffer queue length",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "fluentd_status_buffer_queue_length"
    }
   ]
  },
  {
   "title": "buffer total queued size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "fluentd_status_buffer_total_bytes"
    }
   ]
  },
  {
   "title": "retry count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(fluentd_status_retry_count[5m])"
    }
   ]
  }
 ]
}