- name: Установить зависимости (Docker и docker-compose)
  apt:
    name:
      - docker.io
    state: present
    update_cache: true

- name: Скачать docker-compose v2
  get_url:
    url: "https://github.com/docker/compose/releases/latest/download/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Создать symlink /usr/bin/docker-compose → /usr/local/bin/docker-compose
  file:
    src: /usr/local/bin/docker-compose
    dest: /usr/bin/docker-compose
    state: link
    force: true
